schema_version: 1

context:
  version: "2.2.2"

recipe:
  name: hdbpp-cm-split
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm/-/archive/${{ version }}/hdbpp-cm-${{ version }}.tar.gz
  sha256: c8152a3079af9bd2a69d7c24405379b838d28e08f78f91dd15b1982fa9747d77

build:
  number: 1
  skip: win

outputs:
  - staging:
      name: hdbpp-cm-build
    requirements:
      build:
        - cmake
        - ninja
        - if: unix
          then:
            - pkg-config
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
      host:
        - cppzmq
        - cpptango
        - omniorb-libs
    build:
      script:
        file: build

  - package:
      name: hdbpp-cm
    inherit: hdbpp-cm-build
    build:
      files:
        - if: unix
          then:
            - bin/hdb++cm-srv
    tests:
      - script:
          - hdb++cm-srv --help 2>&1 | grep -i usage

  - package:
      name: hdbpp-cm-dbg
    inherit:
      from: hdbpp-cm-build
      run_exports: false
    build:
      skip:
        - not linux
      dynamic_linking:
        # Prevent dbg file to be modified
        # Will raise CRC mismatch otherwise!
        binary_relocation: false
      files:
        - lib/debug/hdb++cm-srv.dbg
    requirements:
      run:
        - ${{ pin_subpackage('hdbpp-cm', exact=True) }}
    tests:
      - package_contents:
          files:
            - lib/debug/hdb++cm-srv.dbg

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Configuration Manager
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm
  documentation: https://tango-controls.readthedocs.io/en/latest/Explanation/archiving/hdbpp.html

extra:
  feedstock-name: hdbpp-cm
  recipe-maintainers:
    - beenje
